### ISSUE TITLE
Safari - Can't find variable: require in bimserverclient.js

### ISSUE THREAD

**Issue by dbarthelemy** [opensourceBIM/BIMserver-JavaScript-API#4]
Hi, I am setting up a complete DEV environment for BIMserver+API+bimvie+BIMsurfer as explained in the great youtube video but on Mac OS.

BIMserver alone is working just fine in my DEV environment, but as soon as I try to add other projects to Eclipse, I am stuck with "Loading BIMviews..." on screen when trying to open bimvie using Safari.

I was stuck during a while before figuring out that this issue does not appear with Chrome on my Mac.
This must to be linked to Module resolution or loading.

Is there a way to fix this so that we can develop using Safari instead of Chrome on my Mac ?

Same issue also appear if I try to connect using Safari (iOS) or Chrome (Android).
Is there a way to fix this so that we can test the DEV environment directly from mobile devices (iOS/Android) ?

I am starting from GIT Labels:
- BIMserver : 1.5.65
- BIMserver-JavaScript-API : 0.0.108
- bimvie.ws : 0.0.70
- BIMsurfer : 0.0.31

Thanks

**Comment by rubendel** [comment]
Sorry for no response, I don't have access to a mac
