### ISSUE TITLE
%Version% not defined in package.json

### ISSUE THREAD

**Issue by xie-qianyue** [opensourceBIM/BIMserver-JavaScript-API#6]
When I install the project by `npm install`, I have this error:

`npm WARN Invalid version: "%VERSION%"`

And I check the package.json, the vesion key has value "%Version%". I don't know which version it should be, so I didn't give a pull request.

**Comment by rubendel** [comment]
You can just replace it with anything, our build system replaces it with the actual version when making a build. Just a note, I don't think the API is working in NodeJS at the moment.

**Comment by xie-qianyue** [comment]
Ok. I have another question. To add this plugin, I use the way you mention [here](https://github.com/opensourceBIM/BIMserver/wiki/Eclipse), by add the `-plugins` argument. My question is whether I should build this project. As it's a JS project, Maven doesn't do the job I think.

**Comment by rubendel** [comment]
No need to build the project if you just want to use it in Eclipse. BIMserver will automatically serve the content of the project (if you add it with -plugins).

**Comment by xie-qianyue** [comment]
Thank you. I close this issue.

**Comment by xie-qianyue** [comment]
To complete this issue, the version number should be identified with the version of the project, for example, `0.0.135`. Because when I tried `1`, it didn't work.
