### ISSUE TITLE
"Version" 11 instead of 10, Unimplemented version error

### ISSUE THREAD

**Issue by Chris-12** [opensourceBIM/BIMserver-JavaScript-API#9]
Hello,
we have error while loading projects into browser using javascript API.
We have an "Unimplemented version" error.
Looking at the BimServerGeometryLoader.js code looks like :
(line 205)
```
            if (BIMSERVER_VERSION == "1.4") {
	            if (version != 4 && version != 5 && version != 6) {
	                console.error("Unimplemented version");
	                return false;
	            }
            } else {
	            if (version != 10) {
	                console.error("Unimplemented version");
	                return false;
	            }
            }
```
Unfortunately, I did not found what this "version" is about.
In our case, its value is 11 instead of 10.
We use apache-tomcat-8.5.16, jdk1.8.0_131, and bimserverwar-1.5.85.war.
It use to work fine on one Win2012 server, but on many other PCs (mostly Win7), we have this issue.
We could not figure out where does this come from. Would you please let us know what is it about ?
Regards,
Chris .

**Comment by rubendel** [comment]
You need a newer version of the BIMsurfer plugin which is able to handle protocol version 11, you should be able to upgrade it using BIMvie.ws.

**Comment by Chris-12** [comment]
We took last version of bimsurfer tagged "Updated to protocol version 11 (10 is still working too)", and it solved the whole thing on all machines.
Thanks Ruben.
